language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

before_deploy:
  - zip -r lifestudio *
  - mkdir -p deploy
  - mv lifestudio.zip deploy/lifestudio.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: lifestudios3-deploy # 생성한 S3 버킷
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo:  HYLifeStudio/LifeStudio_Backend #Github 주소
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: lifestudios3-deploy # S3 버킷
    key: lifestudio.zip # S3 버킷에 저장된 lifestudio.zip 파일을 EC2로 배포
    bundle_type: zip
    application: lifestudio-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: lifestudio-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: us-east-2
    wait-until-deployed: true
    on:
      repo: HYLifeStudio/LifeStudio_Backend
      branch: main
notifications:
  email:
    recipients:
    - zxcvb5434@likelion.org

hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180


before_install:
  - openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv -in application.yml.enc -out application.yml -d


