spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lifestudio
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  jwt:
    secret : govlepel@$&


logging:
  level:
    org.hibernate.SQL: debug