spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lifestudiodb.crcohu21zbni.us-east-2.rds.amazonaws.com:3306/lifestudio
    username: admin
    password: lifestudio!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  jwt:
    secret : govlepel@$&


logging:
  level:
    org.hibernate.SQL: debug